estoque/urls.py
from django.urls import path
from . import views

app_name = 'estoque'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastrar-produto', views.cadastrar_produto, name='cadastrar_produto'),
    path('update-produto', views.update_produto, name='update_produto'),
    path('delete-produto', views.delete_produto, name='delete_produto'),
]

nunessports/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
     path('', include('estoque.urls'), name='index'),
]

estoque/models.py
from django.db import models

class Produto(models.Model):
    nome = models.CharField(max_length=100)
    codigo_produto = models.CharField(max_length=100)
    descricao = models.TextField()
    preco = models.FloatField()
    status = models.BooleanField(default=True)

estoque/views.py
from django.shortcuts import render, redirect
from . import models

def index(request):
    produtos = models.Produto.objects.filter(status=True)
    return render(request, 'estoque/index.html', {'produtos': produtos})


def cadastrar_produto(request):
    if request.method == 'POST':
        fields = [
            'nome', 'codigo_produto', 'descricao', 'preco',
        ]
        
        field_values = {}
        for field in fields:
            value = request.POST.get(field)
            if value:
                if field == 'preco':
                    value = value.replace(',', '.')
                field_values[field] = value


        new_produto = models.Produto(**field_values)
        new_produto.save()
    return render(request, 'estoque/cadastrar-produto.html',)


def update_produto(request):
    id_produto = None
    if request.method == 'POST':
        fields = [
            'pk', 'nome', 'codigo_produto', 'descricao', 'preco',
        ]
        
        field_values = {}
        for field in fields:
            value = request.POST.get(field)
            if value:
                if field == 'preco':
                    value = value.replace(',', '.')
                if field == 'pk':
                    id_produto = value
                field_values[field] = value


        new_produto, created = models.Produto.objects.update_or_create(
        id=field_values['pk'],
        defaults=field_values
        )

    if request.method == 'GET':
        id_produto = request.GET.get('pk')
        
    produto = models.Produto.objects.get(pk=id_produto)
    
    return render(request, 'estoque/update-produto.html',{'produto': produto})


def delete_produto(request):
    if request.method == 'POST':
        value = request.POST.get('pk')
        if value:
            models.Produto.objects.filter(pk=value).update(status=False)
    return redirect('estoque:index')

estoque/templates/estoque/cadastrar-produto.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'head' %}
    <link href="{% static 'estoque/css/style.css' %}" rel="stylesheet">
{% endblock 'head' %}

{% block 'titulo' %}Nunes Sports{% endblock 'titulo' %}

{% block 'conteudo' %}
<section id="contact" class="intro main-bg section">
    <div class="main-content intro-content">
      <div class="intro-text-content">
        <h2>Cadastrar Produto</h2>
        <p>Esse formulário permitirá o registro detalhado de um novo produto, incluindo nome, código, descrição e preço para melhor organização e gerenciamento.</p>
      </div>
      <div class="contact-form">
        <form action="{% url "estoque:cadastrar_produto" %}" method="POST">
        <fieldset class="form-grid">
          <legend>Por favor, preencha as informações abaixo para cadastrar um novo produto</legend>
           
                {% csrf_token %}
          <div class="form-group">
            <label for="nome">Nome do Produto</label>
            <input type="text" name="nome" id="nome" placeholder="Nome">
          </div>

          <div class="form-group">
            <label for="codicodigo_produtogo">Código do Produto</label>
            <input type="text" name="codigo_produto" id="codigo_produto" placeholder="Código">
          </div>

          <div class="form-group">
            <label for="descricao">Descrição do Produto</label>
            <input type="text" name="descricao" id="descricao" placeholder="Descrição">
          </div>

          <div class="form-group">
            <label for="preco">Preço do Produto</label>
            <input type="text" name="preco" id="preco" placeholder="Preço">
          </div>

          <div class="form-group full-width">
            <button type="submit">Casdastrar</button>
          </div>
       
        </fieldset>
    </form>
      </div>  
    </div>
  </section>
{% endblock 'conteudo' %}

estoque/templates/estoque/index.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'head' %}
    <link href="{% static 'estoque/css/style.css' %}" rel="stylesheet">
{% endblock 'head' %}

{% block 'titulo' %}Nunes Sports{% endblock 'titulo' %}

{% block 'conteudo' %}
<section id="contact" class="intro main-bg section">
    <section id="pricing" class="white-bg section">
        <div class="main-content top3-content">
          <h2>Produtos</h2>
          <p>Essa tabela proporciona uma visão geral dos produtos existentes e oferece opções de edição e exclusão para gerenciar eficientemente o catálogo de produtos disponíveis.
          </p>

          <div class="responsive-table">
            <table>    
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>Código</th>
                  <th>Descrição</th>
                  <th>Preço</th>
                  <th>Editar</th>
                  <th>Apagar</th>
                </tr>
              </thead>
    
              <tbody>
                {% for produto in produtos %}
                    <tr>
                        <td>{{ produto.nome }}</td>
                        <td>{{ produto.codigo_produto }}</td>
                        <td>{{ produto.descricao }}</td>
                        <td>{{ produto.preco }}</td>                        
                        <td>
                            <form action="{% url 'estoque:update_produto' %}" method="POST">
                                {% csrf_token %}
                                <div class="d-flex justify-content-center mt-10">
                                    <input type="text" value="{{produto.pk}}" hidden name="pk" id="pk">
                                    <button type="submit" class="btn bg-white"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                                      </svg></button>
                                </div>
                            </form>
                        </td>
                        <td>
                            <form action="{% url 'estoque:delete_produto' %}" method="POST">
                                {% csrf_token %}
                                <div class="d-flex justify-content-center mt-10">
                                    <input type="text" value="{{produto.pk}}" hidden name="pk" id="pk">
                                    <button type="submit" class="btn btn-danger"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                        <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                                      </svg></button>
                                </div>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </section>
  
{% endblock 'conteudo' %}

estoque/templates/estoque/update-produto.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'head' %}
    <link href="{% static 'estoque/css/style.css' %}" rel="stylesheet">
{% endblock 'head' %}

{% block 'titulo' %}Nunes Sports{% endblock 'titulo' %}

{% block 'conteudo' %}
<section id="contact" class="intro main-bg section">
    <div class="main-content intro-content">
      <div class="intro-text-content">
        <h2>Editar Produto</h2>
        <p>Esse formulário permitirá editar um produto, incluindo nome, código, descrição e preço para melhor organização e gerenciamento.</p>
      </div>
      <div class="contact-form">
        <form action="{% url "estoque:update_produto" %}" method="POST">
        <fieldset class="form-grid">
          <legend>Por favor, atualize as informações abaixo para editar o produto.</legend>
           
                {% csrf_token %}
          <div class="form-group">
            <label for="nome">Nome do Produto</label>
            <input type="text" name="nome" id="nome" value="{{ produto.nome }}" placeholder="Nome">
          </div>

          <div class="form-group">
            <label for="codicodigo_produtogo">Código do Produto</label>
            <input type="text" name="codigo_produto" id="codigo_produto" value="{{ produto.codigo_produto }}" placeholder="Código">
          </div>

          <div class="form-group">
            <label for="descricao">Descrição do Produto</label>
            <input type="text" name="descricao" id="descricao" value="{{ produto.descricao }}" placeholder="Descrição">
          </div>

          <div class="form-group">
            <label for="preco">Preço do Produto</label>
            <input type="text" name="preco" id="preco" value="{{ produto.preco }}" placeholder="Preço">
          </div>

          <input type="text" name="pk" id="pk" value="{{ produto.pk }}" hidden>
          <div class="form-group full-width">
            <button type="submit">Editar</button>
          </div>
       
        </fieldset>
    </form>
      </div>  
    </div>
  </section>
{% endblock 'conteudo' %}